"""Add contact_phone and emergency_contact fields to Booking model

Revision ID: 60214f5c87df
Revises: 
Create Date: 2025-07-06 13:43:15.340980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60214f5c87df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('emergency_contact')
        batch_op.drop_column('contact_phone')

    # ### end Alembic commands ###
