"""Add status field to Tour model

Revision ID: bb60f138357e
Revises: 84b2262b62ad
Create Date: 2025-07-11 20:30:54.202891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb60f138357e'
down_revision = '84b2262b62ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'COMPLETED', 'CANCELLED', name='tourstatus'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
